name: Question Service CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ENV: PROD
      PORT: 8004
      DB_CLOUD_URI: ${{ secrets.DB_CLOUD_URI }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./src/backend/question_backend
        run: npm ci
      - name: Run Tests
        working-directory: ./src/backend/question_backend
        run: npm test